import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    appTitle: 'Krishi Sakhi',
    welcome: 'Your farming companion',
    welcomeFarmer: 'Welcome, Farmer!',
    farmerName: 'John Varghese',
    dashboard: 'Dashboard',
    chat: 'AI Assistant',
    crops: 'My Crops',
    weather: 'Weather',
    activities: 'Activities',
    schemes: 'Schemes',
    location: 'Kerala, India',
    farmName: 'My Farm',
    aiPoweredAssistant: 'An AI-Powered farming assistant for farmers in Kerala, India.',
    availableInBothLanguages: 'Available in English and Malayalam.',
    aiAssistant: 'AI Assistant',
    personalAdvisor: 'Your personal farming advisor.',
    cropManagement: 'My Crops',
    cropManagementDesc: 'Manage and track your crops.',
    weatherInfo: 'Weather',
    weatherDescription: 'Real-time weather information for your area.',
    activityLog: 'Activity Log',
    activityLogDesc: 'Log and track your daily farm activities.',
    govSchemes: 'Government Schemes',
    govSchemesDesc: 'Stay informed about government initiatives.',
    helpSupport: 'Help & Support',
    helpDescription: 'Find answers to common questions and get help.',
    faq: 'Frequently Asked Questions',
    howAddCrops: 'How do I add a new crop?',
    howAddCropsAnswer: 'Navigate to the "My Crops" section and click the "Add Crop" button. Fill in the details and save.',
    weatherAccuracy: 'How accurate is the weather data?',
    weatherAccuracyAnswer: 'The weather data is sourced from real-time meteorological services and is highly accurate for your region.',
    offlineUsage: 'Can I use this app offline?',
    offlineUsageAnswer: 'Some features like the Activity Log can be used offline, and data will sync when you are back online. Other features require an internet connection.',
    notifications: 'Notifications',
    allRead: 'Mark all as read',
    noNewNotifications: 'No new notifications.',
    searchPlaceholder: 'What\'s on your mind?',
    typeMessage: 'Type your message...',
    send: 'Send',
    loading: 'Loading...',
    fetchingWeather: 'Fetching weather data...',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    sunlight: 'Sunlight',
    addCrop: 'Add New Crop',
    cropPlaceholder: 'e.g., Rice, Coconut',
    addActivity: 'Add Activity',
    activityPlaceholder: 'e.g., Fertilizing the paddy field',
    activityDate: 'Date',
    activityDescription: 'Description',
    save: 'Save',
    profile: 'Profile',
    yourProfile: 'Your Profile',
    userId: 'User ID',
    firebase: 'Firebase Details',
    myFarm: 'My Farm',
    myCrops: 'My Crops',
    addActivityQuick: 'Add a Quick Activity',
    viewAll: 'View All',
    searchCrops: 'Search Crops',
    addCropTitle: 'Add a new crop',
    cropName: 'Crop Name',
    cropType: 'Crop Type',
    sowingDate: 'Sowing Date',
    locationField: 'Location',
    addCropButton: 'Add Crop',
    add: 'Add',
    fetchingSchemes: 'Fetching government schemes...',
    updateProfile: 'Update Profile',
    farmLocation: 'Farm Location',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    myActivities: 'My Activities',
    delete: 'Delete',
    noActivities: 'No activities logged yet.',
    noCrops: 'No crops added yet.',
    deleteConfirmation: 'Are you sure you want to delete this?',
    searchSchemes: 'Pravasi',
    speak: 'Speak',
  },
  ml: {
    appTitle: 'കൃഷി സഖി',
    welcome: 'നിങ്ങളുടെ കാർഷിക കൂട്ടുകാരൻ',
    welcomeFarmer: 'സ്വാഗതം, കർഷകരെ!',
    farmerName: 'ജോൺ വർഗീസ്',
    dashboard: 'ഡാഷ്ബോർഡ്',
    chat: 'എഐ അസിസ്റ്റന്റ്',
    crops: 'എന്റെ വിളകൾ',
    weather: 'കാലാവസ്ഥ',
    activities: 'പ്രവർത്തനങ്ങൾ',
    schemes: 'പദ്ധതികൾ',
    location: 'കേരളം, ഇന്ത്യ',
    farmName: 'എന്റെ കൃഷിഭൂമി',
    aiPoweredAssistant: 'കേരളത്തിലെ കർഷകർക്കായുള്ള ഒരു എഐ-അധിഷ്ഠിത കാർഷിക സഹായി.',
    availableInBothLanguages: 'ഇംഗ്ലീഷിലും മലയാളത്തിലും ലഭ്യമാണ്.',
    aiAssistant: 'എഐ അസിസ്റ്റന്റ്',
    personalAdvisor: 'നിങ്ങളുടെ വ്യക്തിപരമായ കാർഷിക ഉപദേഷ്ടാവ്.',
    cropManagement: 'എന്റെ വിളകൾ',
    cropManagementDesc: 'നിങ്ങളുടെ വിളകൾ കൈകാര്യം ചെയ്യുകയും ട്രാക്ക് ചെയ്യുകയും ചെയ്യുക.',
    weatherInfo: 'കാലാവസ്ഥ',
    weatherDescription: 'നിങ്ങളുടെ പ്രദേശത്തെ തത്സമയ കാലാവസ്ഥ വിവരങ്ങൾ.',
    activityLog: 'പ്രവർത്തന രേഖ',
    activityLogDesc: 'നിങ്ങളുടെ ദൈനംദിന കാർഷിക പ്രവർത്തനങ്ങൾ രേഖപ്പെടുത്തുക.',
    govSchemes: 'സർക്കാർ പദ്ധതികൾ',
    govSchemesDesc: 'സർക്കാർ സംരംഭങ്ങളെക്കുറിച്ച് വിവരങ്ങൾ അറിയുക.',
    helpSupport: 'സഹായം',
    helpDescription: 'പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾക്ക് ഉത്തരം കണ്ടെത്തുക.',
    faq: 'പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ',
    howAddCrops: 'എങ്ങനെ ഒരു പുതിയ വിള ചേർക്കാം?',
    howAddCropsAnswer: '"എന്റെ വിളകൾ" വിഭാഗത്തിലേക്ക് പോയി "വിള ചേർക്കുക" ബട്ടണിൽ ക്ലിക്ക് ചെയ്യുക. വിവരങ്ങൾ നൽകി സേവ് ചെയ്യുക.',
    weatherAccuracy: 'കാലാവസ്ഥ വിവരങ്ങൾ എത്രത്തോളം കൃത്യമാണ്?',
    weatherAccuracyAnswer: 'കാലാവസ്ഥ വിവരങ്ങൾ തത്സമയ കാലാവസ്ഥാ സേവനങ്ങളിൽ നിന്ന് ലഭിക്കുന്നതാണ്, ഇത് നിങ്ങളുടെ പ്രദേശത്തിന് വളരെ കൃത്യമാണ്.',
    offlineUsage: 'ഈ ആപ്പ് ഓഫ്‌ലൈനായി ഉപയോഗിക്കാൻ കഴിയുമോ?',
    offlineUsageAnswer: 'പ്രവർത്തന രേഖ പോലുള്ള ചില ഫീച്ചറുകൾ ഓഫ്‌ലൈനായി ഉപയോഗിക്കാം, നിങ്ങൾ ഓൺലൈനിൽ വരുമ്പോൾ ഡാറ്റ സമന്വയിക്കും. മറ്റ് ഫീച്ചറുകൾക്ക് ഇന്റർനെറ്റ് കണക്ഷൻ ആവശ്യമാണ്.',
    notifications: 'അറിയിപ്പുകൾ',
    allRead: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക',
    noNewNotifications: 'പുതിയ അറിയിപ്പുകളൊന്നുമില്ല.',
    searchPlaceholder: 'നിങ്ങളുടെ മനസ്സിൽ എന്താണുള്ളത്?',
    typeMessage: 'നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
    send: 'അയയ്ക്കുക',
    loading: 'ലോഡുചെയ്യുന്നു...',
    fetchingWeather: 'കാലാവസ്ഥ വിവരങ്ങൾ എടുക്കുന്നു...',
    humidity: 'ഈർപ്പം',
    windSpeed: 'കാറ്റിന്റെ വേഗത',
    sunlight: 'സൂര്യപ്രകാശം',
    addCrop: 'പുതിയ വിള ചേർക്കുക',
    cropPlaceholder: 'ഉദാ: നെല്ല്, തെങ്ങ്',
    addActivity: 'പ്രവർത്തനം ചേർക്കുക',
    activityPlaceholder: 'ഉദാ: നെൽപാടത്ത് വളമിടുന്നു',
    activityDate: 'തീയതി',
    activityDescription: 'വിവരണം',
    save: 'സേവ് ചെയ്യുക',
    profile: 'പ്രൊഫൈൽ',
    yourProfile: 'നിങ്ങളുടെ പ്രൊഫൈൽ',
    userId: 'ഉപയോക്തൃ ഐഡി',
    firebase: 'ഫയർബേസ് വിവരങ്ങൾ',
    myFarm: 'എന്റെ കൃഷിഭൂമി',
    myCrops: 'എന്റെ വിളകൾ',
    addActivityQuick: 'പെട്ടെന്ന് ഒരു പ്രവർത്തനം ചേർക്കുക',
    viewAll: 'എല്ലാം കാണുക',
    searchCrops: 'വിളകൾ തിരയുക',
    addCropTitle: 'പുതിയ വിള ചേർക്കുക',
    cropName: 'വിളയുടെ പേര്',
    cropType: 'വിളയുടെ തരം',
    sowingDate: 'വിത്ത് വിതച്ച തീയതി',
    locationField: 'സ്ഥലം',
    addCropButton: 'വിള ചേർക്കുക',
    add: 'ചേർക്കുക',
    fetchingSchemes: 'സർക്കാർ പദ്ധതികൾ എടുക്കുന്നു...',
    updateProfile: 'പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്യുക',
    farmLocation: 'കൃഷിഭൂമിയുടെ സ്ഥലം',
    saveChanges: 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
    cancel: 'റദ്ദാക്കുക',
    myActivities: 'എന്റെ പ്രവർത്തനങ്ങൾ',
    delete: 'നീക്കം ചെയ്യുക',
    noActivities: 'പ്രവർത്തനങ്ങളൊന്നും രേഖപ്പെടുത്തിയിട്ടില്ല.',
    noCrops: 'വിളകളൊന്നും ചേർത്തിട്ടില്ല.',
    deleteConfirmation: 'ഇത് നീക്കം ചെയ്യാൻ നിങ്ങൾ ഉറപ്പാണോ?',
    searchSchemes: 'Pravasi',
    speak: 'സംസാരിക്കുക',
  },
};

const LanguageContext = createContext({
  language: 'en',
  setLanguage: (_lang) => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const t = (key) => translations[language]?.[key] || key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
